name: Check Workflow Dispatch

on:
  repository_dispatch:
    types: [test-repository-dispatch]

jobs:
  echo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "${{ github.event.client_payload.content }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TANUKI_BOX_WEBHOOK_URL }}
